---
title: "Bird Baths"
author:"Antony Rono"
date: 2021-09-04
output: html_output
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(magrittr)
library(hrbrthemes)
library(extrafont)

extrafont::loadfonts()
```

# Load the weekly Data

```{r Load}

tt <- tt_load("2021-08-31")
raw_data <- tt$bird_baths

```

# Number of Sightings Per Bird Species
```{r}
bird_baths_count <- raw_data %>% 
  
  #mutate(bird_type = fct_lump_n(bird_type, 50, w = bird_count)) %>% 
  
  count(bird_type, wt = bird_count, sort = TRUE) %>% 
  
  mutate(bird_type = fct_reorder(bird_type, n),
         
         id = row_number()) %>% 
  
    head(50) #Only top 50 birds


```

# Defining the Labels and Angles of the chart

```{r}

# Get the name and the y position of each label
label <- bird_baths_count

# # Combining Name and Value
# label %<>% 
#   
#   mutate(bird_type = paste0(bird_type, "-","\n", n))


# calculate the ANGLE of the labels
number_of_bar <- nrow(label)
angle <-  90 - 360 * (label$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)

# calculate the alignment of labels: right or left - If I am on the left part of the plot, my labels have currently an angle < -90
label$hjust<-ifelse( angle < -90, 1, 0)

# flip angle to make them readable
label$angle<-ifelse(angle < -90, angle+180, angle)

```

# Creating the Plot

```{r}

# Defining Custom Palette for the bars
custom_palette <- c(rcartocolor::carto_pal(11, "Prism"),
                    rcartocolor::carto_pal(11, "Pastel"),
                    rcartocolor::carto_pal(11, "Antique"),
                    rcartocolor::carto_pal(11, "Vivid"),
                    rcartocolor::carto_pal(11, "Safe"),
                    rcartocolor::carto_pal(11, "Bold")
                    
                    )


# Plottng
bird_baths_count %>% 
  
  ggplot(aes(x=as.factor(id), y=n, fill = bird_type, color = bird_type)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar

  geom_bar(stat="identity", width = 0.2) +
  
  # Limits of the plot = very important. The negative value controls the size of the inner circle, the positive one is useful to add size over each bar. Set the upper limit slightly above than the maximum value to allow space for texts
  ylim(-210,750) +
  
  #Changing color of bars
  scale_fill_manual(values = custom_palette)  +
  
  scale_color_manual(values = custom_palette)  +
  
  # Customize the theme
  hrbrthemes::theme_modern_rc()+
  
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    panel.grid.major.x = element_blank(),
    legend.position  = "none",
    #plot.margin = unit(rep(1.2,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
    ) +
  
  # This makes the coordinate polar instead of cartesian.
  coord_polar(start = 0) +
  
  # Add the labels, using the label data frame that we have created before
  geom_text(data=label,
            aes(x=id, y=n+10, label=bird_type, hjust=hjust), 
            color="white", 
            fontface="bold.italic",
            family = "sans",
            alpha=.8, 
            size=3.5, 
            angle= label$angle, 
            inherit.aes = FALSE ) +
  # Add main text inside the inner circle
  geom_text(
    aes(x = 0, y = -80, label = "Bird Baths"),
    size = 5.5,
    family = "Segoe UI",
    color = "tomato1",
    fontface = "bold"
  )+
  #Add sub text inside the inner circle
  geom_text(
    aes(x = 0, y = -210, label = str_wrap("Occurrence of Australian bird species at bird baths in private gardens", 25)),
    size = 3.3,
    family = "Segoe UI",
    color = "tomato3"
  ) +

  labs(caption = "source: Cleary et al, 2016. | viz: Antony Rono")
  
  
```

# Save Image

```{r}
ggsave("plots/bird_baths.png", 
       bg = "transparent",
       width = 10, 
       height = 11)

````
