---
title: "Water Sources"
author: "Antony Rono
date: 2021-05-08
output: html_output
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
library(magrittr)
library(ggthemes)
library(ggmap)
library(gganimate)
library(highcharter)
library(maps)
library(ggraph)
library(extrafont)

theme_set(theme_light())

```

# Load the weekly Data

```{r Load Date}

tt <- tt_load("2021-05-04")

data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-04/water.csv')

```

## Cleaning Data

```{r}

water <- data %>% 
  
  mutate(report_date = mdy(report_date),
         
         install_year = ifelse(install_year > year(today()), NA_real_, install_year),
         
         status_id = case_when(
           
           status_id == "y" ~ "Working",
           
           status_id == "n" ~ "Not Working",
           
           status_id == "u" ~ "Unknown"
           
         )
         
         ) %>% 
  
  separate(water_tech, into = c("water_tech", "brand"), sep = " - ", fill = "right")


## Retaining African Countries

countries <- get_data_from_map(download_map_data("https://code.highcharts.com/mapdata/custom/africa.js"))

water %<>% 
  
    mutate(country_name = case_when(
    
    country_name == "Congo - Kinshasa" ~ "Democratic Republic of the Congo",
    
    country_name == "Congo - Brazzaville" ~  "Republic of Congo",
    
    country_name == "Tanzania" ~ "United Republic of Tanzania",
    
    TRUE ~ country_name
    )
    ) %>% 
  
  filter(country_name %in% countries$name)


## Removing records that don't have a country

water_countries <- water %>% 
  
  filter(!is.na(country_name))
  

```

### Map of Africa

```{r Map of country by water sources}

library(countrycode)

africa_map_data <- map_data("world") %>% 
  
  as_tibble() %>% 
  
  mutate(continent = countrycode(region, "country.name", "continent")) %>% 
  
  filter(continent == "Africa") %>% 
  
  left_join(water_countries %>% count(country_name), by = c("region" = "country_name")) %>% 
  
  mutate(n = coalesce(n,0))


africa_map <- africa_map_data %>% 
  
  ggplot(aes(long, lat, group = group,fill = n), color  = "gray") +
  
  geom_polygon() +
  
  theme_map() +
  
  theme(legend.position = c(0.25, 0.30), 
        
        legend.background = element_rect(fill = "#add8e6",
                                         linetype = "blank"),
        
        legend.text = element_text(size = 10),
        
        legend.key.size = unit(0.4, "cm"),
        
        legend.title = element_blank())+
  
  scale_fill_gradientn(colours = terrain.colors(7)) +
  
  scale_colour_continuous(labels=comma)

africa_map

```


# Uganda

```{r Uganda maps}

water_uganda <- water %>% 
  
  filter(country_name == "Uganda",
         
         between(lat_deg, -2,4),
         
         between(lon_deg, 29, 35)) %>% 
  
  mutate(water_source_lumped = fct_lump(water_source, 5),
         
         water_source_lumped = fct_reorder(water_source_lumped, water_source, length, .desc = TRUE)) %>% 
  
  replace_na(list(water_source_lumped = "Other"))



# water_uganda %>%
# 
#   ggplot(aes(lon_deg, lat_deg, color = water_source ))+
# 
#   borders("world", regions = "Uganda")+
# 
#   geom_point(size = .1, alpha = .25) +
# 
#   theme_map() +
# 
#   theme(legend.position = "bottom")


bbox <- c(left = 29.2, right = 35, bottom = -2, top = 4)
         
uganda_map <- get_stamenmap(bbox, zoom = 7, maptype = "terrain" )

## Overall
overall_map <- ggmap(uganda_map) +
  
  geom_point(aes(lon_deg, lat_deg ),
             
             data = water_uganda, size = .1, alpha = .1, color = "#660066") +
  
  theme_map() +
  
  theme(legend.position = "none")

## Faceted
map_faceted <- ggmap(uganda_map) +
  
  geom_point(aes(lon_deg, lat_deg ),
             
             data = water_uganda, 
             size = .1,
             alpha = .1,
             color = "#663366") +
  
  facet_wrap(~water_source_lumped, strip.position = "top", ncol = 6,labeller = label_wrap_gen(10)) +
  
  theme_map() +
  
  theme(panel.border = element_rect(colour = "black", fill = NA),
        
        strip.text = element_text(size = 10)
        )

```


```{r Combining plots}

library(cowplot)

ggdraw()+
  
  draw_plot(africa_map, x = 0, y = .45, width = .45, height = .55, hjust = 0.1) +
  
  draw_plot(map_faceted, x = 0, y = 0, width = 1, height = 1, vjust = 0.25) +
  
  draw_plot(overall_map, x = .4, y = .55, width = .4, height = .4, hjust = 0.25) +
  
  annotate("curve", x = 0.26, xend = 0.4, y = 0.75, yend = 0.7, size=1,
           
           color = "#3399FF", curvature = 0.2) +
  
  draw_text(family = "Bodoni MT",x = .82, y = 0.85,
             
            text = "Water Access Points in Uganda", color = "black", fontface = "bold", size = 16
            
             ) +
  
      draw_text(family = "Bodoni MT",x = .82, y = 0.75,
            
            text = "Uganda has the highest number of water access points in Africa.\nThese are mostly concentrated in the eastern and south-western\nparts of the country",
            
            color = "black", fontface = "bold", size = 9) +
  
    draw_text(family = "Bodoni MT",x = .82, y = 0.65,
            
            text = "Boreholes are the most common sources, roughy spread out\nacross the country but with a higher concentration in the\n northern part ofLake Victoria.",
            
            color = "black", fontface = "bold", size = 9) +

    draw_text(family = "Bodoni MT",x = .82, y = 0.55,
            
            text = "Protected springs and undefined shallow wells are located\nclose to water sources.",
            color = "black", fontface = "bold", size = 9)+
  
  theme(
    
    plot.background = element_rect(
      
      fill = "#add8e6"),
    
    plot.caption = element_text(color = "#CCCCCC", size = 10)
    
  ) +
  
    
```

## Not Included -Animated Map

```{r Animated Map}

point_anime_data <- water_uganda %>% 
  
  filter(!is.na(install_year)) %>% 
  
  mutate(install_year = pmax(1990, install_year)) %>% 
  
  mutate(year = map(install_year, ~seq(., 2021))) %>% 
  
  unnest(year)
  
  
# point_anime_data %>%  
#   
#   ggplot(aes(lon_deg,lat_deg)) +
#   
#   borders("world", regions = "Uganda") +
#   
#   geom_point(size = .1, alpha = .25, color = "#663366") +
#   
#   theme_map() +
#   
#   transition_manual(year) +
#   
#   labs(title = "Water sources in Uganda in year: { current_frame }")
# 
  
ggmap(uganda_map) +
  
  geom_point(aes(lon_deg, lat_deg ),
             
             data = point_anime_data,
             size = .1, 
             alpha = .1,
             color = "#663366") +
  
  transition_manual(year) +
  
  labs(title = "Water sources in Uganda in year: { current_frame }")

```


# Save Image

```{r}

# This will save your most recent plot

ggsave(
  filename = "./plots/water_access_points.png",
  device = "png"
  )

```
