---
title: "TidyTemplate"
author: "Antony Rono"
date: 2021-05-25
output: html_output
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
library(ggalt)
library(ggtext)
library(hrbrthemes)
library(extrafont)

options(scipen = 99)
theme_set(theme_light())
loadfonts()

```

# Load the weekly Data

```{r Load data}

tt <- tt_load("2021-05-25")

records <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/records.csv')
drivers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/drivers.csv')


```

```{r plot}


records %>%
  
   # select only 3-lap times
   filter(type == "Three Lap") %>% 
  
   # calculate the average time per track per shortcut/not
   group_by(shortcut, track) %>% 
  
   summarise(meantime = mean(time)) %>% 
  
   pivot_wider(names_from = shortcut, values_from = meantime) %>%    # put shortcut or not into their own columns
   
  
   mutate(diff = No - Yes) %>%   # Difference between shortcut/not
  
   drop_na(diff) %>% 
  
   mutate(track = fct_reorder(track, diff),
         
         lab = Yes + 0.5*diff,
         
         mean = mean(diff)) %>% 
  
  #Plotting
   ggplot(aes(y = track, x = Yes, xend = No, color = diff)) +
  
   geom_dumbbell(size = 5, colour_xend = "red", colour_x = "forestgreen", dot_guide = FALSE) +

   geom_vline(aes(xintercept = 0),linetype = "dashed", color = "white") + 
  
   geom_vline(aes(xintercept = mean(diff)), color = "olivedrab4", linetype = "dashed", size = 2.0) +
  
   geom_text(aes(x = lab, label=round(diff,1)), 
                color="white",
                size=3.5, 
                hjust=-0, 
                vjust = -1) +
  
   annotate("curve", x = 78.9, y = "Royal Raceway" , xend = 268,yend = "Yoshi Valley", color = "palegreen1",curvature = .18, size = 1,arrow=arrow(length=unit(0.2,"cm"))) +

   annotate("text", x = 300, y = "Yoshi Valley", label = "Shortcuts save an\naverage of 79 seconds\nin a 3-lap course", 
            color = "violet",
            size = 4.5) +
   
   annotate("text", x = 22.6, y = "Wario Stadium" , label = "Fastest time using shortcut\nis 22.6 seconds",
            color = "blueviolet",
            size = 3.5,
            vjust = 1.3,
            hjust = .5) +
  
  annotate("text", x = 88.9, y = "Mario Raceway" , label = "Fastest time using the\nlong road is 88.9 seconds", 
            color = "blueviolet",
           size = 3.5,
            vjust = .5,
           hjust = -0.1) +
  
  annotate("curve", x = 358, y = "Rainbow Road" , xend = 312,yend = "D.K.'s Jungle Parkway", color = "tomato1", curvature = .3, size = 1,arrow=arrow(length=unit(0.2,"cm"))) +

  annotate("text", x = 295, y = "Rainbow Road" , label = "Slowest time using the\nlong road is 358 seconds",
            color = "wheat",
           size = 3.5,
            vjust = 2.5,
           hjust = 0) +
  
  annotate("text", x = 215, y = "Rainbow Road" , label = "Slowest time using\nshortcut is 215 seconds",
            color = "wheat",
           size = 3.5,
            vjust = 1.3,
           hjust = 0.5) +
  
   scale_color_gradient(low = "grey90", high = "grey30") +

   theme_modern_rc() + 

   theme(plot.title = element_text(size = 18),
         plot.subtitle = element_markdown(lineheight = 1.1),
         plot.caption = element_text(color = "grey90"),
         panel.grid.major.y = element_line(linetype = "dashed", color = "grey90"),
         axis.text.y = element_text(color = "white", size = 14),
         axis.text.x = element_text(color = "white", size = 14), 
         axis.title.x = element_text(color = "grey90", size=12), 
         legend.position = "none") +

   labs(title = "Mario Kart World Records: On Which Track Does Shortcut Save the Most Time?", 
        
        subtitle = "World records that <span style='color:forestgreen;'>**take the shortcut**</span> are 
        always <span style='color:white;'>faster</span> than records that <span style='color:red;'>**take the long road**</span>.
        <br>The most time saved by <span style='color:forestgreen;'>**taking the shortcut**</span> 
        is <span style='color:white;'>242.6 seconds</span> on the Wario Stadium track.",
        fill = NULL, color = NULL, y = NULL, x = "Average record time for a 3-lap course (seconds)",
        caption = "source :Mario Kart World Records | viz: Antony Rono") 

```

```{r save plot}

ggsave("plots/mario_kart_world_records.png", 
       bg = "transparent", 
       width = 14, 
       height = 8, 
       dpi = 600)


```

