---
title: "Kenya Census"
author: "Antony Rono"
date: 2021-04-17
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=8)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggthemes)
library(ggpubr)
library(RColorBrewer)
library(rKenyaCensus)
library(patchwork)
library(sp)
library(sf)

theme_set(theme_light())

options(scipen = 99)

```

# Loading and Cleaning Data

```{r Load, include=FALSE}

tt <- tt_load("2021-01-19")

tt %>% 
  
  map(glimpse)


gender <- tt$gender %>% 
  
  clean_names() %>% 
  
    mutate(county = str_to_title(county))


household <- tt$households %>% 
  
  clean_names() %>% 
  
  mutate(county = str_replace(county, "([a-z])([A-Z])", "\\1 \\2"),
         
         county = str_to_title(county)) %>% 
  
    mutate(county = (str_trim(county))
           
           )

crops <- tt$crops %>% 
  
  clean_names() %>% 
  
  rename(county = sub_county) %>% 
  
  mutate(county = str_to_title(county)
         
         ) 
```

# Kenyan Map

```{r Kenyan Map of Population}

kenya_sf <- KenyaCounties_SHP %>%
  
  st_as_sf() %>% 
  
  st_simplify(dTolerance = 200) %>% 
  
  clean_names() %>% 
  
  mutate(county = str_to_title(county)) %>% 
  
  select(-population) %>% 
  
  left_join(household, by = "county") %>% 
  
  left_join(gender %>% select(-total), by = "county") 




kenya_sf %>% 

  ggplot(aes(fill = population))+
  
  geom_sf(data = kenya_sf) +
  
  scale_fill_distiller(palette = "Spectral")+
  
  ggsflabel::geom_sf_label_repel(aes(label = county),  size = 1.6)+
  
  #geom_sf_text(aes(label = county))+
  
  theme_map() + 
  
  theme(plot.title = element_text(size = 30, hjust = .5))+
  
  labs(title = "Kenyan Population by County")
  
```


```{r Saving the most recent plot}

ggsave(
  filename = "./plots/kenya_census.png",
  device = "png")

```
